
## API REST

#  Clientes


### Testar a adição de um novo cliente  OK
POST http://localhost:5000/api/clientes
Content-Type: application/json

{
    "nome": "João da Silva",
    "email": "joao.silva@example.com",
    "telefone": "11949224355"
}

###

### Testar a recuperação de todos os clientes  OK
GET http://localhost:5000/api/clientes
Accept: application/json

###

### Testar a recuperação de um cliente específico pelo ID  ok
GET http://localhost:5000/api/clientes/2
Accept: application/json

###

### Testar a atualização de um cliente existente    OK
PUT http://localhost:5000/api/clientes/2
Content-Type: application/json

{
    "nome": "João da Silva Atuali",
    "email": "joao.silva.atualizado@example.com",
    "telefone": "11949224355"
}

###

### Testar a exclusão de um cliente   OK
DELETE http://localhost:5000/api/clientes/2
Accept: application/json


################################################################


### Criar um Fornecedor  OK
POST http://localhost:5000/api/fornecedores
Content-Type: application/json

{
  "Nome": "Fornecedor Teste",
  "Contato": "Contato do Fornecedor",
  "Telefone": "12345678"
}

###

### Obter Todos os Fornecedores  OK
GET http://localhost:5000/api/fornecedores
Accept: application/json



### Atualizar um Fornecedor Existente  OK
PUT http://localhost:5000/api/fornecedores/3
Content-Type: application/json

{
    "FornecedorID": 3,
    "Nome": "Fornecedor Atualizado",
    "Contato": "Contato Atualizado",
    "Telefone": "8765-4321"
}

###

### Deletar um Fornecedor  OK
DELETE http://localhost:5000/api/fornecedores/2

###


########################################################

### Adicionar um novo produto  OK
POST http://localhost:5000/api/produtos
Content-Type: application/json

{
    "nome": "Produto Exemplo",
    "preco": 19.99,
    "fornecedorID": 3
}

### Obter todos os produtos  OK
GET http://localhost:5000/api/produtos
Accept: application/json

###

### Obter um produto por ID  OK
GET http://localhost:5000/api/produtos/3
Accept: application/json


### Atualizar um produto OK

PUT http://localhost:5000/api/produtos/3
Content-Type: application/json

{
    "ProdutoID": 3,
    "nome": "Produto Atualizado",
    "preco": 29.99,
    "FornecedorID": 3
}

###

### Deletar um produto pelo ID  OK  
DELETE http://localhost:5000/api/produtos/3
Accept: application/json

###


##########################################

#  API JSON EXTERNA 

### Endpoint para verificar os dados armazenados  OK
GET http://localhost:5000/api/dadosapi
Content-Type: application/json

#
----

### Importar Posts da API Externa
POST http://localhost:5000/api/posts/importar
Content-Type: application/json



################################################

## NOTAS
### Criar uma nova Nota Fiscal  OK
POST http://localhost:5000/api/notafiscal
Content-Type: application/json

{
    "numero": "NF123456",
    "dataEmissao": "2024-10-29T00:00:00",
    "valor": 150.75,
    "descricao": "Venda de produtos eletrônicos",
    "clienteID": 5,
    "dataVenda": "2024-10-29T00:00:00"
}

### Obter todas as notas fiscais  OK
GET http://localhost:5000/api/notafiscal
Accept: application/json


### Atualizar uma Nota Fiscal existente  OK
PUT http://localhost:5000/api/notafiscal/5
Content-Type: application/json

{
    "notaFiscalID": 3,
    "numero": "NF123456atual",
    "dataEmissao": "2024-10-29T00:00:00",
    "valor": 350.00,
    "descricao": "Venda de produtos eletrônicos atualiza",
    "clienteID": 5,
    
    "dataVenda": "2024-10-29T00:00:00"
}


### Deletar uma Nota Fiscal OK
DELETE http://localhost:5000/api/notafiscal/5
